---
# Using Ansible, configure three VLANs on the Arista switch specifying both the 
 # VLAN IDs and the VLAN names.  For the VLAN IDs randomly pick three numbers 
 # between 100 and 999.

 - name: Arista-Ansible Exercise1
   hosts: arista

   tasks:
     - name: create VLANs 
       eos_vlan: name={{ item.vlan_name }} vlanid={{ item.vlan_id }}
             username={{ eapi_username }}
             password={{ eapi_password }}
             host={{ eapi_hostname }}
             port={{ eapi_port }}
             transport=https
       with_items:
         - {vlan_name: v221, vlan_id: 221}
         - {vlan_name: v222, vlan_id: 222}
         - {vlan_name: v223, vlan_id: 223}



